function(find_arch)
    set(ARCH "")
    if(("${CMAKE_CXX_COMPILER_ID}" STREQUAL MSVC) OR
       ("${CMAKE_CXX_COMPILER_ID}" STREQUAL Intel))
        if("${CMAKE_GENERATOR}" MATCHES "(Win64|IA64|intel64)")
            set(ARCH x64)
        else()
            set(ARCH x86)
        endif()
    elseif(("${CMAKE_CXX_FLAGS}" MATCHES -m64) OR
           (${CMAKE_SIZEOF_VOID_P} EQUAL 8))
        set(ARCH x64)
    elseif(("${CMAKE_CXX_FLAGS}" MATCHES -m32) OR
           (${CMAKE_SIZEOF_VOID_P} EQUAL 4))
        set(ARCH x86)
    else()
        message(FATAL_ERROR "Unknown architecture, please specify -DARCH=<ARCH>")
        return()
    endif()
    set(ARCH "${ARCH}" CACHE STRING "Architecture" FORCE)
endfunction()

if("${ARCH}" STREQUAL "")
    find_arch()
endif()
